export const childrennavdata =  [{
    name:'filter',
    title:'筛选器',
    list:[{
        name:'已完成的',
        url:'/filter/filter/1',
        routername:'1'
    },{
        name:'分配给我的',
        url:'/filter/filter/2',
        routername:'2'
    },{
        name:'未完成的',
        url:'/filter/filter/3',
        routername:'3'
    },{
        name:'分配给我的',
        url:'/filter/filter/4',
        routername:'4'
    },{
        name:'已完成的',
        url:'/filter/filter/5',
        routername:'5'
    },{
        name:'分配给我的',
        url:'/filter/filter/6',
        routername:'6'
    },{
        name:'未完成的',
        url:'/filter/filter/7',
        routername:'7'
    }]
},{
    name:'seeting',
    title:'项目设置',
    url:'/projects/seeting/',
    params:'projectname',
    query:'id',
    list:[{
        name:'详细信息',
        routername:'seetinginformation'
    },{
        name:'权限',
        routername:'seetingpermission'
    },{
        name:'通知',
        routername:'seetingnotice'
    }]
},{
    name:'spaceseeting',
    title:'空间设置',
    list:[{
        name:'详细信息',
        url:'/knowledgebase/spacedetail/seetinginformation',
        routername:'seetinginformation'
    },{
        name:'权限',
        url:'/knowledgebase/spacedetail/seetingpermission',
        routername:'seetingpermission'
    }]
},{
    name:'userseeting',
    title:'账户设置',
    list:[{
        name:'个人资料',
        url:'/seeting/user/personaldocument',
        routername:'personaldocument'
    },{
        name:'电子邮件',
        url:'/seeting/user/personalemail',
        routername:'personalemail'
    },{
        name:'安全性',
        url:'/seeting/user/editpassword',
        routername:'editpassword'
    }]
},{
    name:'systemseeting',
    title:'系统设置',
    list:[{
        name:'常规配置',
        url:'/seeting/system/ViewApplicationProperties',
        routername:'ViewApplicationProperties'
    },{
        name:'审计日志',
        url:'/seeting/system/ViewApplicationProperties',
        routername:'2'
    },{
        name:'项目角色',
        url:'/seeting/system/ViewApplicationProperties',
        routername:'3'
    },{
        name:'全局权限',
        url:'/seeting/system/ViewApplicationProperties',
        routername:'4'
    },{
        name:'事务收集器',
        url:'/seeting/system/ViewApplicationProperties',
        routername:'5'
    },{
        name:'默认用户首选项',
        url:'/seeting/system/ViewApplicationProperties',
        routername:'6'
    },{
        name:'默认仪表板',
        url:'/seeting/system/ViewApplicationProperties',
        routername:'7'
    },{
        name:'外观',
        url:'/seeting/system/ViewApplicationProperties',
        routername:'8'
    },]
},{
    name:'tasksettings',
    title:'事务设置',
    type:'url',
    list:[{
        name:'优先级',
        url:'/seeting/tasksettings/priority',
        routername:'priority',
    },{
        name:'状态',
        url:'/seeting/tasksettings/state',
        routername:'state',
    }]
},{
    name:'work',
    title:'我的工作',
    type:'url',
    list:[{
        name:'我的事务',
        url:'/mytask',
        routername:'mytask',
        icon:'shiwu'
    },{
        name:'个人日历',
        url:'/mycalendar',
        routername:'mycalendar',
        icon:'rili'
    },{
        name:'日报',
        url:'/daily',
        routername:'daily',
        icon:'ribao'
    }]
}]
